"""initial

Revision ID: b0f670bab941
Revises: 
Create Date: 2026-08-23 18:27:54.580695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0f670bab941'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('listings_buyer_uid_fkey'), 'listings', type_='foreignkey')
    op.drop_constraint(op.f('listings_location_id_fkey'), 'listings', type_='foreignkey')
    op.drop_table('locations')
    op.add_column('listings', sa.Column('spot_in_queue', sa.Integer(), nullable=False))
    op.add_column('listings', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('listings', sa.Column('lng', sa.Float(), nullable=False))
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.drop_column('listings', 'buyer_uid')
    op.drop_column('listings', 'location_id')
    op.drop_column('listings', 'status')
    op.add_column('transactions', sa.Column('stripe_payment_intent_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('completed_transactions', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'completed_transactions')
    op.drop_column('users', 'stripe_account_id')
    op.drop_column('transactions', 'stripe_payment_intent_id')
    op.add_column('listings', sa.Column('status', postgresql.ENUM('available', 'sold', 'cancelled', name='listingstatus'), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('buyer_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('listings_location_id_fkey'), 'listings', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('listings_buyer_uid_fkey'), 'listings', 'users', ['buyer_uid'], ['firebase_uid'])
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_column('listings', 'lng')
    op.drop_column('listings', 'lat')
    op.drop_column('listings', 'spot_in_queue')
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    # ### end Alembic commands ###
